name: "Publish Helm Chart"
description: "Push Helm Charts"
inputs:
  VERSION:
    description: "The version for the workflow run"
    required: true

  TAG:
    description: "The tag for the workflow run"
    required: false
    default: ""

  HELM_REGISTRY:
    description: "The chart repository to push the chart"
    required: true
  
  CONTAINER_REGISTRY_URL: 
    description: "Base registry URL"
    required: false
    default: ""

  RELEASE_BRANCH:
    description: Release branch to push changes
    required: false
    default: main

  OPM_VERSION:
    description: OPM CLI version to use
    default: "v1.50.0"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.12.3

    - name: Build and push chart
      run: make helm-release
      shell: bash
      env:
        VERSION: ${{ inputs.VERSION }}
        GIT_TAG: ${{ inputs.TAG }}
        HELM_REGISTRY: ${{ inputs.HELM_REGISTRY }}
        DOCKER_REPO_BASE: ${{ inputs.CONTAINER_REGISTRY_URL }}
