name: Deleting a branch for versioned doc

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Check if the deleted branch is a version branch
        id: branch_check
        uses: MeilCli/regex-match@v1
        with:
          regex_pattern: '^[0-9]+\.[0-9]+$'
          search_string: ${{ github.event.ref }}

      - name: Checkout source files
        if: steps.branch_check.outputs.matched == 'true'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        if: steps.branch_check.outputs.matched == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install doc tools
        if: steps.branch_check.outputs.matched == 'true'
        run: pip3 install mkdocs-material mkdocs-mermaid2-plugin mike

      - name: Configure Git user
        if: steps.branch_check.outputs.matched == 'true'
        run: |
          git config --local user.email "github-root@stakater.com"
          git config --local user.name "stakater-github-root"

      - name: Delete removed version
        if: steps.branch_check.outputs.matched == 'true'
        run: mike delete --push ${{ github.event.ref }}

      - name: Push Latest Tag
        if: steps.branch_check.outputs.matched == 'true'
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
