name: Deleting a branch for versioned doc

on:
  workflow_call:
    inputs:
      LATEST_DOC_VERSION:
        description: Define the latest doc version for multiple versioned doc
        required: true
        type: string
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true

jobs:
  check:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    outputs:
      matched: ${{ steps.branch_check.outputs.matched }}
    steps:
      - name: Check if the deleted branch is a version branch
        id: branch_check
        uses: MeilCli/regex-match@v1
        with:
          regex_pattern: '^[0-9]+\.[0-9]+(\.[0-9]+)?$'
          search_string: ${{ github.event.ref }}
  delete:
    needs: check
    if: needs.check.outputs.matched == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Install mike
        run: pip3 install mike

      - name: Run prepare_theme.sh script from repository to merge theme_common and theme_override folders
        run: |
          chmod +x prepare_theme.sh
          ./prepare_theme.sh

      - name: Configure Git user
        run: |
          git config --local user.email "stakater@gmail.com"
          git config --local user.name "stakater-user"

      - name: Delete the version and all its aliases from the branch
        run: mike delete --push ${{ github.event.ref }}

      - name: Update 'latest' alias to latest doc version
        run: mike alias --push --update-aliases ${{ inputs.LATEST_DOC_VERSION }} latest

      - name: Push Latest Tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
