name: Operator PR Request

on:
  workflow_call:
    inputs:
      KIND_VERSION:
        description: Kind version to use
        default: "v0.29.0"
        required: false
        type: string
      
      ENABLE_STAKATER_AB_GIT_AUTH:
        description: "Configure git to use stakater-ab private repos"
        required: false
        default: false
        type: boolean  
    
    secrets:
      CONTAINER_REGISTRY_URL:
        description: "Registry URL to publish image"
        required: true

      CONTAINER_REGISTRY_USERNAME:
        description: "Registry username to login"
        required: true

      CONTAINER_REGISTRY_PASSWORD:
        description: "Registry password to login"
        required: true
      
      STAKATER_AB_REPOS:
        description: "GitHub token with access to stakater-ab repos"
        required: false
      
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Configure private repo
        if: ${{ inputs.ENABLE_STAKATER_AB_GIT_AUTH }}
        run: |
          git config --global url."https://${{ secrets.STAKATER_AB_REPOS }}:x-oauth-basic@github.com/stakater-ab".insteadOf "https://github.com/stakater-ab"
          
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          version: ${{ inputs.KIND_VERSION }}

      - name: Find Latest Image Tag
        id: find_tag
        uses: ./.github/actions/operator/last-image
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Operator
        run: |
          make deploy TAG=${{ steps.find_tag.outputs.PR_TAG }}
      
      - name: Run Operator E2E Tests
        run: make test-e2e