name: Documentation Quality Assurance

on:
  workflow_call:
    inputs:
      MD_CONFIG:
        description: Markdown link checker config file
        required: true
        type: string
      DOC_SRC:
        description: Documentation directory
        required: true
        type: string
      MD_LINT_CONFIG:
        description: Markdown lint config file
        required: true
        type: string

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ${{inputs.MD_CONFIG}}
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          max-depth: 3

  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          submodules: recursive
      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v3.9.1/vale_3.9.1_Linux_64-bit.tar.gz -O vale.tar.gz
          tar -xvzf vale.tar.gz vale
          rm vale.tar.gz
      - name: Spell check
        run: |
          ./vale sync
          ./vale ${{inputs.DOC_SRC}}

  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Style check
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          reporter: github-pr-review
          level: error
          language: 'en-US'
          patterns: '**/*.md'

  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: markdown linting check
        uses: DavidAnson/markdownlint-cli2-action@v18.0.0
        with:
          globs: ${{inputs.DOC_SRC}}
          separator: ' '
          config: ${{inputs.MD_LINT_CONFIG}}
