name: Pull Request Sanity Checks

on:
  workflow_call:
    inputs:
      JIRA_PROJECT:
        description: JIRA projects to check against, separated by bar
        required: true
        type: string

jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Description is not empty
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{github.event.pull_request.body}}
          regex: '^$|\s+'
          flags: gm

      - name: Title contains JIRA ticket
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '(${{inputs.JIRA_PROJECT}})-\d+'
