name: Closing a pull request for versioned doc

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Store the current head ref as a url friendly variable
        id: current_branch
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          url_friendly_branch=$(echo ${HEAD_REF} | sed -e 's/[]:@\/?&=#%+[\!$()*,;]/-/g')
          echo "CURRENT_BRANCH=$(echo ${url_friendly_branch})" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install mike
        run: pip3 install mike

      - name: Run prepare_theme_pr.sh script from repository to merge theme_common and theme_override folders
        run: |
          chmod +x prepare_theme_pr.sh
          ./prepare_theme_pr.sh

      - name: Configure Git user
        run: |
          git config --local user.email "stakater@gmail.com"
          git config --local user.name "stakater-user"

      - name: Delete redundant PR deployment
        run: mike delete --push -b pull-request-deployments ${{ steps.current_branch.outputs.CURRENT_BRANCH }}

      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message-success: "@${{ github.actor }} PR doc deploy was successfully deleted from branch pull-request-deployments"
          message-failure: "@${{ github.actor }} PR doc deploy failed to be deleted on branch pull-request-deployments!"
          allow-repeats: true
