name: Pull request for versioned doc

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true

env:
  # Store the current head ref as a url friendly variable
  CURRENT_BRANCH: ${HEAD_REF//\//-}

jobs:
  deploy_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install plugins
        run: pip3 install mike mkdocs-mermaid2-plugin

      - name: Run prepare_theme_pr.sh script from repository to merge theme_common and theme_override folders
        run: |
          chmod +x prepare_theme_pr.sh
          ./prepare_theme_pr.sh

      - name: Configure git user
        run: |
          git config --local user.email "stakater@gmail.com"
          git config --local user.name "stakater-user"

      - name: Deploy PR docs
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: mike deploy --push -b pull-request-deployments $CURRENT_BRANCH

      - name: Update 'latest' alias to latest PR build
        run: mike alias --push -b pull-request-deployments --update-aliases $CURRENT_BRANCH latest

      - name: When publishing a new version, always update the alias to point to the latest version
        run: mike set-default --push -b pull-request-deployments latest

      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message-success: "@${{ github.actor }} PR doc deploy will soon be available for review on https://stakater.github.io/mto-docs/${CURRENT_BRANCH}"
          message-failure: "@${{ github.actor }} PR doc deploy failed!"
          allow-repeats: true
