name: Closing a pull request for versioned doc

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install doc tools
        run: pip3 install mkdocs-material mkdocs-mermaid2-plugin mike

      - name: Configure Git user
        run: |
          git config --local user.email "github-root@stakater.com"
          git config --local user.name "stakater-github-root"

      - name: Delete redundant PR deployment
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: mike delete --push -b pull-request-deployments $HEAD_REF
