name: Pull Request

on:
  workflow_call:
    inputs:
      HELM_PACKAGE_NAME:
        description: name for helm package
        required: true
        type: string
    secrets:
      CONTAINER_REGISTRY_URL:
        description: "Container registry to publish docker image"
        required: true
      CONTAINER_REGISTRY_USERNAME:
        description: "Username to login to container registry"
        required: true
      CONTAINER_REGISTRY_PASSWORD:
        description: "Password to login to container registry"
        required: true

jobs:
  package-and-push-helm-chart:
    name: Package and Push Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Generate Tag
        id: generate_tag
        run: |
          version="$(git describe --tags --abbrev=0)"
          number="pr${{ github.event.pull_request.number }}"
          echo "GIT_TAG=$(echo ${version}-${number})" >> $GITHUB_OUTPUT

      # Set up helm binary
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.2

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Test and Package Helm Chart
        run: |
          sed -i "s/^version:.*/version: ${{ steps.generate_tag.outputs.GIT_TAG }}/" helm/Chart.yaml
          helm lint helm/
          helm -n test template ${{ inputs.HELM_PACKAGE_NAME }} helm/
          helm package helm/

      - name: Push Helm Chart to Registry
        run: |
          helm push ${{ inputs.HELM_PACKAGE_NAME }}-${{ steps.generate_tag.outputs.GIT_TAG }}.tgz oci://ghcr.io/stakater/charts
