name: Container Push and Git Tag

on:
  workflow_call:
    inputs:
      DOCKER_FILE_PATH:
        description: Docker file path
        required: true
        type: string
      BUILD_PARAMETERS:
        description: Docker build parameters
        default: ""
        required: false
        type: string
      RELEASE_BRANCH:
        description: Release branch to push changes
        required: true
        type: string
    secrets:
      CONTAINER_REGISTRY_URL:
        description: "Container registry to publish docker image"
        required: true
      CONTAINER_REGISTRY_USERNAME:
        description: "Username to login to container registry"
        required: true
      CONTAINER_REGISTRY_PASSWORD:
        description: "Password to login to container registry"
        required: true
      SLACK_WEBHOOK_URL:
        description: "Secret to send success/failure message to slack"
        required: true
      GH_TOKEN:
        description: "GitHub token"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Generate Tag
        id: generate_tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: ${{ inputs.RELEASE_BRANCH }}
          DRY_RUN: true

      - name: Generate container image repository path
        run: |
          echo CONTAINER_IMAGE_REPOSITORY=$(echo ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.10.6
          buildkitd-flags: --debug

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.DOCKER_FILE_PATH }}
          pull: true
          push: true
          build-args: BUILD_PARAMETERS=${{ inputs.BUILD_PARAMETERS }}
          cache-to: type=inline
          tags: |
            ${{ env.CONTAINER_IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.new_tag }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          message-success: "@${{ github.actor }} Image is available for testing. `docker pull ${{ env.CONTAINER_IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.new_tag }}`"
          message-failure: "@${{ github.actor }} Yikes! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!"
          allow-repeats: false

      - name: Push Latest Tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: ${{ inputs.RELEASE_BRANCH }}

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        if: always() # Pick up events even if the job fails or is canceled.
        with:
          status: ${{ job.status }}
          fields: repo,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
