name: Push versioned doc

on:
  workflow_call:
    inputs:
      LATEST_DOC_VERSION:
        description: Define the latest doc version for multiple versioned doc
        required: true
        type: string
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install mike
        run: pip3 install mike mkdocs-mermaid2-plugin

      - name: Run prepare_theme.sh script from repository to merge theme_common and theme_override folders
        run: |
          chmod +x prepare_theme.sh
          ./prepare_theme.sh

      - name: Configure Git user
        run: |
          git config --local user.email "stakater@gmail.com"
          git config --local user.name "stakater-user"

      - name: Deploy content
        run: mike deploy --push ${{ github.ref_name }}

      - name: Update 'latest' alias to latest doc version
        run: mike alias --push --update-aliases ${{ inputs.LATEST_DOC_VERSION }} latest

      - name: When publishing a new version, always update the alias to point to the latest version
        run: mike set-default --push latest

      - name: Push Latest Tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
